# Generated by Django 5.1.1 on 2024-10-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
